let {PythonShell} = require('python-shell')
var path = require("path")

// Executable generated by pyinstaller under dist folder
// Saved as foo for linux, foo.exe for Windows, foo.app for Mac
// TODO: add --windowed to pyinstaller to run without popups
// TODO: change to child_process to run executable of python script in final bundled executable

function get_custom_folder_name(){
	var accountName = document.getElementById("custom_folder_name").value
	//document.getElementById("account_name").value = ""; // set back to NULL
	
	var options = {
		scriptPath: path.join(__dirname, '/./'),
		args: ["-F" + accountName],
		// argsparse python -F 'custom_folder_name'
	}
	//console.log(options)
	let handwriting = new PythonShell("csvBackup.py", options);
	handwriting.on('message', function(message) {
		swal(message); // alerting system from python
	})
}
